### ISSUE TITLE
[request]: GRPC Healthchecks 

### ISSUE THREAD

**Issue by smy2748** [aws/aws-app-mesh-roadmap#76] opened 2019-06-12 20:13 UTC
**Tell us about your request**
My team has been creating a lot of GRPC services recently to cut down on client code creation.  We had hoped App Mesh would expose Envoy's grpc healthcheck configuration in some manner so we could use it (https://www.envoyproxy.io/docs/envoy/v1.7.0/api-v2/api/v2/core/health_check.proto#core-healthcheck-grpchealthcheck).  

**Which integration(s) is this request for?**
AppMesh + Fargate

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Currently we're relying on running a simplistic second service to take http traffic to a specific port and forward the call via grpc to the actual service in order to perform healthchecks.  It would be better performance-wise to be able to set up healthchecks that were able to directly call the grpc service.

**Are you currently working around this issue?**
Side service that accepts http, makes a grpc call, and returns the health that way

**Additional context**

**Attachments**

**Comment by lavignes** [comment] 2019-08-24 01:08
Resolving as a duplicate of #96

**Closed by lavignes** 2019-08-24 01:08 UTC
Labels: Proposed
