### ISSUE TITLE
Bug: ECS tasks fail when specifying >15 ignored egress ports

### ISSUE THREAD

**Issue by bigdefect** [aws/aws-app-mesh-roadmap#269] opened 2020-10-05 21:43 UTC
**Summary**
When utilizing the App Mesh integration with ECS, you can specify the "egress ignored ports" for traffic that should not be routed through Envoy. There is a kernel limit of 15 ports per iptables rule that is currently not validated. Creating a task with >15 ports will cause the task to fail.

![egress_ports](https://user-images.githubusercontent.com/3759279/95135157-e0611380-0718-11eb-94dd-1fc387458d50.png)

**Are you currently working around this issue?**
How are you currently solving this problem?

No workaround at the moment.

**Comment by andrnj** [comment] 2020-10-15 16:10
We've identified the cause of the issue, and the fix is non-trivial. In the meantime, we've submitted a documentation update (which you can track here: https://github.com/awsdocs/aws-app-mesh-user-guide/pull/27) to clearly state the limitation.

Eliminating this limitation requires more extensive work, and I'm re-assigning this ticket to the appropriate owner for definition and prioritization.

**Closed** 2024-09-05 22:09 UTC
Labels: Bug, Docs, App Mesh Envoy
