### ISSUE TITLE
Feature Request: Open Telemetry Tracing

### ISSUE THREAD

**Issue by driverpt** [aws/aws-app-mesh-roadmap#441] opened 2022-10-26 11:02 UTC
*If you want to see App Mesh implement this idea, please upvote with a :+1:.*

**Tell us about your request**
OpenTelemetry Support

**Which integration(s) is this request for?**
All applicable

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
OpenTelemetry is the new Standard in observability and given that AWS already has the ADOT Distribution, it would be a major improvement to have this

**Are you currently working around this issue?**
Have Jaeger Tracing receiver on Collector.

**Additional context**
N/A

**Attachments**
N/A

**Comment by ytsssun** [comment] 2022-10-26 21:57
Looks like a duplicate of https://github.com/aws/aws-app-mesh-roadmap/issues/439

**Comment by driverpt** [comment] 2022-10-26 22:52
Oops. My bad....

**Closed** 2022-10-26 22:52 UTC
