### ISSUE TITLE
[request]: Cross Region Routing

### ISSUE THREAD

**Issue by lewislabs** [aws/aws-app-mesh-roadmap#97] opened 2019-08-28 11:31 UTC
**Tell us about your request**
Support for cross region routing with AppMesh. 

**Which integration(s) is this request for?**
All ideally but ECS, EC2 and Fargate would be the priority for me. 

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
We have services that run in a number of AWS regions (and accounts) and would like to be able to use AppMesh to connect these services and manage routing through a single control plane. 
A service runs in a particular region because it's been latency optimized for a specific set of users but we also run some core shared microservices in another region that are dependencies. We can replicate these core services across regions but there's a significant overhead there (including database replication) that we would like to avoid. 

**Are you currently working around this issue?**
VPC Peering and using custom service discovery routing (not using AppMesh) 

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by isaac-mj** [comment] 2019-09-18 14:28
Hello guys,

We currently have the same need for cross-region routing as we have a set of services distributed across the world with a set of core services running only in a single region.

@lewislabs - I've noticed that you mentioned that you worked around this problem with VPC Peering and a custom service discovery? Would you be able to give me more details (either on this thread or privately?)

We are considering Consul as an alternative but I would much rather stick to AWS.

Thx,
Isaac.

**Comment by dastbe** [comment] 2019-09-26 18:58
@lewislabs and @isaac-mj 

would a #37 (Managed Ingress) get you far enough? This would allow you to have multiple meshes in distinct regions, while still having your core mesh that others could talk to via its ingress.

**Comment by shubharao** [comment] 2019-09-26 21:54
@lewislabs Can you please tell us more about the custom service discovery routing - what exactly does it do? 
@isaac-mj If you can create a mesh for each region but represent the core service that runs in one region using a DNS name, would that meet your use case? Are you looking for more routing controls for the connection cross region?

**Comment by lewislabs** [comment] 2019-09-27 12:34
@dastbe I think managed ingress could solve the problem, but maybe I need some more clarity on what managed ingress looks like. 

The problem we have is can be described by this simple example. 

```
Service A exists in an AppMesh in us-east-1. 
Service B exists in an AppMesh in eu-west-1. 
Service B would like to call Service A. 
```
I believe we could quite easily achieve the above with inter-region VPC peering + Managed Ingress?

But now if we deployed instances of Service B into the mesh in us-east-1. Would there be a way for traffic to preference sticking within the same region where it can or is this something that's going to require additional custom configuration?

**Comment by lewislabs** [comment] 2019-09-27 12:36
@shubharao 

When I say custom service discovery that's probably the wrong term. We run an instance of eureka and have custom libraries built around that to do routing based on the eureka service repository.

**Comment by shubharao** [comment] 2019-09-28 01:14
@lewislabs 
>>I believe we could quite easily achieve the above with inter-region VPC peering + Managed Ingress?
Yes, that is our recommended approach. We are researching on how to support the ingress use case (https://github.com/aws/aws-app-mesh-roadmap/issues/37). Since both AWS Cloud Map and AWS App Mesh are regional services, the service discovery and app mesh routing will keep traffic within the region. Further, we are investigating how to enable the AZ aware routing use case (https://github.com/aws/aws-app-mesh-roadmap/issues/94).

**Comment by lewislabs** [comment] 2019-09-30 10:11
@shubharao sounds like both #37 and #94 could solve the problem. Thanks!

**Comment by shubharao** [comment] 2019-10-01 12:59
Closing this issue as duplicate of the two that we are already tracking - modeling ingress services  (#37) and Zone aware routing (#94). If you have other use cases for requiring a mesh that spans across regions or for routing across regions, please open a new one.

**Closed by shubharao** 2019-10-01 12:59 UTC
Labels: Roadmap: More Input needed, Roadmap: Proposed
