### ISSUE TITLE
Support upstream timeout

### ISSUE THREAD

**Issue by stefanprodan** [aws/aws-app-mesh-roadmap#53] opened 2019-04-02 13:59 UTC
Allow the upstream timeout to be specified. 
https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route.proto#envoy-api-field-route-routeaction-timeout

**Comment by TrueBurn** [comment] 2019-08-08 17:01
Even when adding the "x-envoy-upstream-rq-timeout-ms" header to the request to override the default 15s timeout requests still error out with upstream request timeout.

https://www.envoyproxy.io/docs/envoy/latest/configuration/http_filters/router_filter#x-envoy-upstream-rq-timeout-ms

**Comment by stphivos** [comment] 2019-09-11 15:00
Attempting to override using header `x-envoy-upstream-rq-timeout-ms` is ignored for me also. As a result when under heavy load all our slow responses get terminated at the gateway level. Would really appreciate an update on this :)

**Comment by SleeperSmith** [comment] 2019-09-18 02:41
Any update on this? We are blocked on a full roll out because of this.

**Comment by efe-selcuk** [comment] 2019-09-25 01:11
We're researching this right now to see why the header isn't being honored.

**Comment by SleeperSmith** [comment] 2019-10-01 04:21
1. Yes
2. Yes
3. Yes.

The downstream requester: Nginx as ingress controller -> envoy proxy
The upstream responder: Custom app service registered as a virtual service + virtual router + virtual node.

**Comment by dastbe** [comment] 2019-10-03 19:36
A quick update on why this isn't working.

Broadly, the issue is an interaction between how envoy [determines if the request is internal](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers#x-forwarded-for) (which is what allows the use of envoy control headers) and the setting of use_remote_address.

Currently, App Mesh configuration does turns use_remote_address *off*. The result is that at the downstream doesn't consider the request internal (as no x-forwarded-for is set) and x-forwarded-for is not appended to, and the upstream will not respect the control header for the same reason.

Looking forward, we'd like to support upstream timeouts on both the route (respected at the downstream) and on a VNode listener (respected at the upstream).

**Comment by stphivos** [comment] 2019-10-10 11:10
@efe-selcuk, @dastbe thanks. In our case a standard request is as follows:

```
[client] => [aws alb] => [nginx] => [flask-http-app] => [grpc-tcp-app] => [aws rds]
```

where `nginx` (vn), `flask` (vs+vn) and `grpc` (vs+vn) are all modeled in App Mesh and have the Envoy Proxy sidecar. All were updated to support higher timeouts (3m) but when some responses are slow `nginx` replies with 504. As a temp solution we removed the services from the mesh.

**Comment by SleeperSmith** [comment] 2019-10-14 22:47
@stphivos that sounds like the timeout is working? What settings / host headers did you set? I have a similar set up and that should work well enough for me.

Can't you just set nginx timeout to something higher?

**Comment by stphivos** [comment] 2019-10-28 12:34
@SleeperSmith both `aws alb` and `nginx gateway` have timeouts set to `3m`:

```
http {
    server {
        listen 80;
        server_name _;
        proxy_http_version 1.1;

        client_header_timeout  3m;
        client_body_timeout    3m;
        send_timeout           3m;
        keepalive_timeout      3m;

        gzip on;
        gzip_min_length  1100;
        gzip_buffers     4 8k;
        gzip_types       text/plain;

        location / {
            try_files $uri @app;
        }

        location @app {
            proxy_redirect  off;
            proxy_pass      http://backend;

            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Host $server_name;

            proxy_connect_timeout  70;
            proxy_send_timeout     180;
            proxy_read_timeout     180;            
        }
    }
}
```

The request times out at `nginx` while waiting for the `flask app` to respond. I can confirm that from `X-Ray`:
```
mymesh/service-gateway-vn AWS::AppMesh::Proxy
  => mymesh/service-gateway-vn  504 15.0 sec

mymesh/flask-app-vn AWS::ECS::Container
  => mymesh/flask-app-vn        200 16.4 sec
```

Also when logging the http headers at the flask app i get:
```
  "X-Real-Ip": "127.0.0.1",
  "X-Forwarded-For": "<public-ip-addr>, 127.0.0.1",
  "X-Forwarded-Host": "_",
  "X-Envoy-Expected-Rq-Timeout-Ms": "15000"
```

I tried setting different headers from the http client but still no luck:
```
x-envoy-upstream-rq-timeout-ms          180000
x-envoy-upstream-rq-per-try-timeout-ms  180000
X-Envoy-Expected-Rq-Timeout-Ms          180000
```

`X-Envoy-Expected-Rq-Timeout-Ms` in the request is always set to `15000` and the client receives a 504: upstream request timeout.

I'm using the latest release of appmesh-inject (v0.2.0) which uses `aws-appmesh-envoy:v1.11.2.0-prod`. Thanks.

**Comment by gdowmont** [comment] 2019-11-20 15:25
I have got an application that streams the response back to the client. Due to the size it can take more than a minute to finish. However envoy always terminates the connection after 15 seconds. 

I have tried sending keep-alives, chunking, streaming, it is always 15 seconds and connection gets closed.

Are there any workarounds I could try applying? As other mentioned before, header are being ignored.
I have tried with the latest `aws-appmesh-envoy:v1.12.1.0-prod`

**Comment by craiggoddenpayne** [comment] 2019-11-20 16:31
I have the same issue also, I came across this after searching for some time, and `x-envoy-expected-rq-timeout-ms` does not seem to work for me also.

I also cannot find any mention of this in any documentation on the AWS site, only on envoy documentation, is AppMesh now support changing the timeout based on request headers like in the envoy documentation? https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/router_filter

**Comment by SleeperSmith** [comment] 2019-12-04 01:18
@bcelenza so this has been accepted as being worked on, but I'm just wondering why I don't see it on the project road map. Just want to see if this is being worked on or this is under a slightly different status?

**Comment by bcelenza** [comment] 2019-12-04 21:36
@SleeperSmith sorry about that, added it to the roadmap project. We are actively working on it now. 😄

**Comment by gary-cowell** [comment] 2019-12-13 07:36
Imagine my disappointment upon getting 29 meshed services deployed with CDK only to find a slew of hard limit 15s timeouts. This is not usable in this state. Awaiting a resolution.

**Comment by hanxu2050** [comment] 2020-03-11 00:23
any update on this? we also just migrated 2 of our applications to App Mesh and now facing time out issues

**Comment by SleeperSmith** [comment] 2020-03-11 03:08
Just to chime in here. We've withheld further roll out of AWS AppMesh specifically because of this too. Some 15 something services.

**Comment by LancerRainier** [comment] 2020-04-06 18:59
Hey just to give a quick update, this is still work in progress but we are getting more traction here. We had some delays in early 2020, and is now back on track. We are looking at launching this in Q2 2020 (most likely in May 2020). Will keep this thread updated if any more changes. Apologies about the delay here, we are aware that this is a very high priority item and are actively working on it. Thanks!

**Comment by shwetasahuit** [comment] 2020-04-08 21:19
As part of providing support for timeouts, we intend to add configurable timeout fields( request timeout and idle timeout) at the Route, Virtual Node listener and probably at the Virtual Gateway listener too.

**Comment by shwetasahuit** [comment] 2020-05-30 00:06
Hi All, Timeouts for Routes and Virtual Node Listener are available for testing in our [preview channel](https://docs.aws.amazon.com/app-mesh/latest/userguide/preview.html). Check out the [walkthrough](https://github.com/aws/aws-app-mesh-examples/tree/master/walkthroughs/howto-timeout-policy) to get started. Refer to the docs for [route](https://docs.aws.amazon.com/app-mesh/latest/userguide/routes.html#awsui-expandable-section-3) and [Virtual Node](https://docs.aws.amazon.com/app-mesh/latest/userguide/virtual_nodes.html#virtual-node-listener-timeout) for more info.

Looking forward for your feedback.

**Comment by shwetasahuit** [comment] 2020-06-19 00:31
Timeouts is now [available](https://aws.amazon.com/about-aws/whats-new/2020/06/aws-app-mesh-introduces-timeout-configuration-support/) in the App Mesh APIs, SDKs and Console for all regions. The Kubernetes controller supports timeout in the latest version [v1.0.0](https://aws.amazon.com/about-aws/whats-new/2020/06/aws-app-mesh-controller-for-kubernetes-is-now-generally-available/)

Timeout configuration is supported at [route](https://docs.aws.amazon.com/app-mesh/latest/userguide/routes.html) and at [Virtual Node listeners](https://docs.aws.amazon.com/app-mesh/latest/userguide/virtual_nodes.html). Refer API docs and the userguide for more information.

Please note that the Cloudformation support is not released yet, It will be available soon.

**Comment by herrhound** [comment] 2020-06-19 22:25
Closing the issue, as the feature is now released.

**Closed by herrhound** 2020-06-19 22:25 UTC
Labels: Priority: High, Roadmap: Accepted

**Comment by RafalMaleska** [comment] 2021-04-16 14:23
hi, the issue was solved for VirtualNodes but how about VirtualGateway? 

it there a way to set the timeout on them?

**Comment by RafalMaleska** [comment] 2021-04-23 14:19
ok, solved this by using a router and setting a timeout for one of the routes.

**Comment by visit1985** [comment] 2021-11-05 10:43
Even when setting timeouts on VirtualRouter and VirtualNode level, the is still no timeout defined on VirtualGateways internal self-redirect to 15001. This should be set to the max of all timeouts across all possible routes, but is currently defaulting to 15s.

**Comment by rajal-amzn** [comment] 2021-11-05 15:40
@visit1985 Thank you for reporting this. We are aware of this regression where the timeouts are not getting configured at Virtual Gateway when the hostname rewrite is disabled. We are currently working on the fix and is being tracked [here](https://github.com/aws/aws-app-mesh-roadmap/issues/376)
